services:
#   # Development environment
#   client:
#     build: 
#       context: ./client
#       target: dev
#     ports:
#       - "5173:5173"
#     depends_on:
#       - server
#     restart: always
#   server:
#     build: 
#       context: ./server
#       target: dev
#     ports:
#       - "3000:3000"
#     #networks:
#      # - car-rental
#     #depends_on:
#      # - mongo
#     #restart: always

#   #mongo:
#    # image: mongo:latest
#    # ports:
#    #   - "27017:27017"
#    # networks:
#    #   - car-rental
#    # volumes:
#     #  - mongo-data:/data/db
#     #restart: always

# #volumes:
#  # mongo-data:
# #networks:
#  # car-rental:
#    # driver: bridge

   
  # Production environment
  client:
    build: ./client
    image: hetgajera01/carrental-client
    ports:
      - "8000:80"

    depends_on:
      - server
    networks:
      - car-rental
    restart: always

  server:
    build: ./server
    image: hetgajera01/carrental-server
    ports:
      - "3000:3000"

    networks:
      - car-rental
    restart: always
networks:
  car-rental:
    driver: bridge
